class AdGroup < ApplicationRecord
  # extends ...................................................................
  # includes ..................................................................
  include AdParentStatusController
  include ViewMethod

  # security (i.e. attr_accessible) ...........................................
  # relationships .............................................................
  belongs_to :campaign, optional: true
  belongs_to :client
  belongs_to :manager, optional: true
  has_many :ads, dependent: :destroy

  delegate :name, to: :campaign, prefix: true
  # validations ...............................................................
  validates_presence_of :name, :client_id

  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  acts_as_paranoid

  # class methods .............................................................
  # public instance methods ...................................................

  # protected instance methods ................................................
  # private instance methods ..................................................
end
