class Campaign < ApplicationRecord
# extends ...................................................................
# includes ..................................................................
  include AdParentStatusController
  include ViewMethod

# security (i.e. attr_accessible) ...........................................
# relationships .............................................................
  belongs_to :client
  belongs_to :manager, optional: true
  has_many :ads
  has_many :ad_groups, dependent: :destroy

  delegate :name, to: :manager, prefix: true
# validations ...............................................................
  validates_presence_of :client_id, :name, :daily_budget

# callbacks .................................................................
  after_commit :set_ads_campaign_id
# scopes ....................................................................
# additional config .........................................................
  acts_as_paranoid

# class methods .............................................................
# public instance methods ...................................................
# protected instance methods ................................................
# private instance methods ..................................................
  private

  def set_ads_campaign_id
    # reset campaign_id if ad_group change
    if previous_changes.key?(:ad_group_id)
      Ad.where(campaign_id: id).update_all(campaign_id: nil)
      Ad.where(ad_group_id: ad_groups.ids).update_all(campaign_id: id)
    end
  end
end
