class DailySignageReport < ApplicationRecord
  # extends ...................................................................
  # includes ..................................................................
  include ViewMethod
  # security (i.e. attr_accessible) ...........................................
  # relationships .............................................................
  belongs_to :signage

  # validations ...............................................................
  validates_presence_of :faces, :clicks, :impressions, :created_at_date,
                        :faces_cost, :clicks_cost, :impressions_cost, :signage_id

  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  # class methods .............................................................
  # public instance methods ...................................................
  def signage_id_with_title
    "[#{signage_id}]  #{title.to_s}"
  end

  # protected instance methods ................................................
  # private instance methods ..................................................
end
