class DailyManagerReport < ApplicationRecord
  # extends ...................................................................
  # includes ..................................................................
  # security (i.e. attr_accessible) ...........................................
  # relationships .............................................................
  belongs_to :manager

  # validations ...............................................................
  validates_presence_of :faces, :clicks, :impressions, :created_at_date, :name,
                        :faces_cost, :clicks_cost, :impressions_cost, :manager_id

  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  # class methods .............................................................
  # public instance methods ...................................................
  def manager_id_with_name
    "[#{manager_id}]  #{name.to_s}"
  end

  # protected instance methods ................................................
  # private instance methods ..................................................
end
