class DailyAdReport < ApplicationRecord
  # extends ...................................................................
  # includes ..................................................................
  include ViewMethod
  # security (i.e. attr_accessible) ...........................................
  # relationships .............................................................
  belongs_to :ad

  # validations ...............................................................
  validates_presence_of :faces, :clicks, :impressions, :created_at_date,
                        :faces_cost, :clicks_cost, :impressions_cost, :ad_id

  # callbacks .................................................................
  # scopes ....................................................................
  scope :yesterday, -> { where(created_at_date: Date.current-1.days) }

  # additional config .........................................................
  # class methods .............................................................
  # public instance methods ...................................................
  def ad_id_with_name
    "[#{ad_id}]  #{name.to_s}"
  end

  def cost
    faces_cost + clicks_cost + impressions_cost
  end

  # protected instance methods ................................................
  # private instance methods ..................................................
end
