class DailyShopReport < ApplicationRecord
  # extends ...................................................................
  # includes ..................................................................
  # security (i.e. attr_accessible) ...........................................
  # relationships .............................................................
  belongs_to :shop

  # validations ...............................................................
  validates_presence_of :faces, :clicks, :impressions, :created_at_date,
                        :faces_cost, :clicks_cost, :impressions_cost, :shop_id

  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  # class methods .............................................................
  # public instance methods ...................................................
  def shop_id_with_title
    "[#{shop_id}]  #{title.to_s}"
  end

  # protected instance methods ................................................
  # private instance methods ..................................................
end
