class Shop < ApplicationRecord
  # extends ...................................................................
  # includes ..................................................................
  include ViewMethod

  # security (i.e. attr_accessible) ...........................................
  # relationships .............................................................
  has_many :signages, dependent: :nullify
  has_many :daily_shop_reports

  belongs_to :client
  # validations ...............................................................
  validates_presence_of :title, :telephone, :client_id

  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
