class SignageAdUnit < ApplicationRecord
  # extends ...................................................................
  # includes ..................................................................
  include AdParentStatusController

  # security (i.e. attr_accessible) ...........................................
  # relationships .............................................................
  belongs_to :client
  belongs_to :ad_template
  has_many :signage_ad_unit_contents
  has_many :ads, through: :signage_ad_unit_contents

  # validations ...............................................................
  validates_presence_of :mode, :title , :refresh_script_hour, :refresh_ad_second,
                        :ad_template_id, :client_id

  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  enum mode: { random: '0', specific: '1' }
  accepts_nested_attributes_for :signage_ad_unit_contents,
                                reject_if: proc { |attr| attr[:position] == '0' && attr[:ad_id].blank? },
                                allow_destroy: true

  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
