class User < ApplicationRecord
  # extends ...................................................................
  # includes ..................................................................
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable

  # security (i.e. attr_accessible) ...........................................
  # relationships .............................................................
  belongs_to :client

  # validations ...............................................................
  validates_presence_of :client_id, :name

  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
